name: csac-action-test

on:
  push:
  pull_request:

jobs:
  csac:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Auto Cert
        uses: neobaran/csac-action@v1.0.0
        with:
          version: latest
          tencent-secret-id: ${{ secrets.TENCENT_SECRET_ID }}
          tencent-secret-key: ${{ secrets.TENCENT_SECRET_KEY }}
          domains: |
            test.neobaran.com